## counts_links table definition
---
name: polls
primarykey: id
engine: InnoDB
charset: utf8
autoincrement:
    colname: id
    start: 1
cols:
    id:
        type: bigint
        length: 20
        params: NOT NULL
    text:
        type: varchar
        length: 255
        params: NOT NULL
    maxreplies:
        type: bigint
        length: 20
        params: NOT NULL
    isclosed:
        type: bool
        length: 
        params: 
    showarchive:
        type: bool
        length: 
        params: 
    votessum:
        type: bigint
        length: 20
        params: NOT NULL
    starttime:
        type: bigint
        length: 20
        params: NOT NULL
    stoptime:
        type: bigint
        length: 20
        params: NOT NULL
    voteexpiration:
        type: bigint
        length: 20
        params: NOT NULL
    createtime:
        type: bigint
        length: 20
        params: NOT NULL
    createuser:
        type: bigint
        length: 20
        params: NOT NULL
indices:
    text:
        col: text
        isUnqiue: false
    isclosed:
        col: isclosed
        isUnqiue: false
    showarchive:
        col: showarchive
        isUnqiue: false
    starttime:
        col: starttime
        isUnqiue: false
    stoptime:
        col: stoptime
        isUnqiue: false
    archived_all:
        col: 
            stoptime
            isclosed
            showarchive
        isUnqiue: false
    archived_small:
        col: 
            isclosed
            showarchive
        isUnqiue: false
defaultvalues:
    rows:
